### ISSUE TITLE
Unexpected transformation of metadata

### ISSUE THREAD

**Issue by remjx** [paulelie/winston-pg-native#3]
Why is flatted `stringify` method used to encode the metadata object that is logged? Why not use standard `JSON.stringify`? @petpano

**Comment by remjx** [comment]
also posted the question on the forked-from repo https://github.com/ofkindness/winston-pg-native/issues/12

**Comment by petpano** [comment]
Hello @markjackson02, i guess it's for avoid an Circular JSON error..  i think that it's possible to have another trick to avoid it, but i didn't work on it sincerely.., if you have an solution/alternative, don't hesitate to share it, i'll take it :)

**Comment by petpano** [comment]
As i answered, i mark it as closed :)

**Comment by remjx** [comment]
I forked the repo to get around the issue https://github.com/remjx/winston-pg-native
